---
# tasks file for src/roles/common

- include: epel.yml
  tags: epel

- include: dnf.yml
  tags: dnf_update

- include: common_{{ansible_distribution }}_{{ ansible_distribution_major_version }}.yml
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "9"
  tags: common_tools

- include: common_{{ansible_distribution }}_{{ ansible_distribution_major_version }}.yml
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "8"
  tags: common_tools
