---
# defaults file for src/roles/init

- name: Install firewalld
  become: true
  dnf:
    name: firewalld
    state: present

- name: Start firewalld
  become: true
  systemd:
    state: started
    name: firewalld
    enabled: true

- name: Set firewalld service
  become: true
  firewalld:
    zone: "{{ item.zone }}"
    service: "{{ item.service }}"
    permanent: "{{ item.permanent }}"
    state: "{{ item.state }}"
    immediate: "{{ item.immediate }}"
  with_items: "{{ firewalld_service }}"
  when: firewalld_service is defined
  notify: Restart firewalld
