---
# handlers file for src/roles/master_user

- name: Restart webserver
  become: true
  service:
    name: "{{ web_server_service_name }}"
    state: restarted
    enabled: true
  when:
    - not ansible_check_mode
