---

- name: Install openssl
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl
  notify:
    - Restart webserver
    - Restart firewalld

- name: Install httpd
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ httpd_dependencies }}"
  notify:
    - Restart webserver
    - Restart firewalld

- name: Install mod_ssl
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - mod_ssl
  notify:
    - Restart webserver
    - Restart firewalld

- name: Change permission Document Root {{ httpd_document_root }}
  become: true
  file:
    path: "{{ httpd_document_root }}"
    state: "directory"
    owner: "{{ web_user.name }}"
    group: "{{ web_user.name }}"
    mode: "775"
#    recurse: yes
  notify:
    - Restart webserver
    - Restart firewalld

- name: Change permission Document Root {{ httpd_document_root }}{{ httpd_public_dir }}
  become: true
  file:
    path: "{{ httpd_document_root }}{{ httpd_public_dir }}"
    state: "directory"
    owner: "{{ web_user.name }}"
    group: "{{ web_user.name }}"
    mode: "775"
#    recurse: yes
  notify:
    - Restart webserver
    - Restart firewalld

- name: Make index.html
  become: true
  template:
    src: templates/index.html.j2
    dest: "{{ httpd_document_root }}{{ httpd_public_dir }}/index.html"
    owner: "{{ web_user.name }}"
    group: "{{ web_user.name }}"
    mode: '0644'

- name: Make phpinfo
  become: true
  template:
    src: templates/phpinfo.php.j2
    dest: "{{ httpd_document_root }}{{ httpd_public_dir }}/phpinfo.php"
    owner: "{{ web_user.name }}"
    group: "{{ web_user.name }}"
    mode: '0644'
