---
# tasks file for src/roles/webserver

- include: web_user_add.yml
  tags:
    - httpd
    - nginx

- include: httpd.yml
  when: web_server_service_name == 'httpd'
  tags:
    - httpd

- include: nginx.yml
  when: web_server_service_name == 'nginx'
  tags:
    - nginx

- include: firewalld.yml
  tags:
    - webserver_firewalld
