---
# handlers file for src/roles/init

- name: Restart sshd
  become: true
  systemd:
    state: restarted
    name: sshd
    enabled: true

- name: Restart firewalld
  become: true
  systemd:
    state: restarted
    name: firewalld
    enabled: true
