---
# defaults file for src/roles/init

ansible_ssh_user: root
ansible_port: 22
ansible_ssh_pass: '{{ secret.root_user_password }}'
host_key_checking: false
ask_pass: true

firewalld_service:
  - service: 'ssh'
    zone: 'public'
    permanent: 'yes'
    state: 'enabled'
    immediate: true
