---
# tasks file for src/roles/docker

- name: Check installed docker
  command: "docker --version"
  register: docker_exists
  changed_when: false
  ignore_errors: true

- name: Debug
  debug:
    msg: "{{ docker_exists }}"

- name: Install Docker repo
  become: true
  command: 'dnf config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo'
  when: docker_exists.failed is true

- name: Install Docker
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_list: "{{ docker_dependencies }}"
  notify: service_docker_enabled


- name: Add docker group
  become: true
  user:
    name: "{{ item.value.name }}"
    groups: docker
    append: true
  with_dict: "{{ users }}"
  when:
    - docker_users is defined

- name: Add docker group ansible-user
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true

- name: Check exist docker deamon service file
  become: true
  stat:
    path: "/etc/systemd/system/docker.service.d/startup_options.conf"
  register: exists_docker_deamon

- name: Docker deamon dir
  become: true
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: "directory"
    mode: 0775
  when:
    - exists_docker_deamon.stat.exists is false

- name: Docker deamon service.conf
  become: true
  template:
    src: templates/startup_options.conf.j2
    dest: "/etc/systemd/system/docker.service.d/startup_options.conf"
    mode: 0775
  when:
    - exists_docker_deamon.stat.exists is false

- name: Docker demon check
  become: true
  shell: |
    set -o pipefail
    bash -lc "service docker status | grep '0.0.0.0:{{ dockerd_port }}' | wc -l"
  changed_when: false
  register: docker_deamon_service

- name: Debug
  debug:
    msg: "{{ docker_deamon_service.stdout }}"

- name: Reload systemd docker
  become: true
  shell: |
    bash -lc "systemctl daemon-reload"
    bash -lc "systemctl restart docker.service"
  when:
    - docker_deamon_service.stdout == "0"
